// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // NOTE:
  // Project bạn đang dùng: ung-dung-hoc-tieng-anh-a0580 (theo android/app/google-services.json)
  // File này trước đó đang trỏ sang project khác (..-348fd) nên gây “upload không thấy dữ liệu”.
  //
  // Các thông số Android lấy trực tiếp từ google-services.json (a0580).
  // Với Windows/Web: hiện repo chưa có cấu hình Web AppId riêng của a0580,
  // nên tạm thời dùng chung appId Android để seed dữ liệu từ desktop.
  // Khi bạn tạo Web app trên Firebase Console, mình có thể cập nhật lại appId web/windows chuẩn.

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA00nCu19ojVU93niKFJaUNmGc4ynBPyTc',
    appId: '1:16215337124:android:c49d3bb0968e33ae175e31',
    messagingSenderId: '16215337124',
    projectId: 'ung-dung-hoc-tieng-anh-a0580',
    authDomain: 'ung-dung-hoc-tieng-anh-a0580.firebaseapp.com',
    storageBucket: 'ung-dung-hoc-tieng-anh-a0580.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA00nCu19ojVU93niKFJaUNmGc4ynBPyTc',
    appId: '1:16215337124:android:c49d3bb0968e33ae175e31',
    messagingSenderId: '16215337124',
    projectId: 'ung-dung-hoc-tieng-anh-a0580',
    storageBucket: 'ung-dung-hoc-tieng-anh-a0580.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA00nCu19ojVU93niKFJaUNmGc4ynBPyTc',
    // TODO: Nếu bạn dùng iOS/macOS, cần tạo app iOS trong Firebase a0580 để lấy appId iOS đúng.
    appId: '1:16215337124:android:c49d3bb0968e33ae175e31',
    messagingSenderId: '16215337124',
    projectId: 'ung-dung-hoc-tieng-anh-a0580',
    storageBucket: 'ung-dung-hoc-tieng-anh-a0580.firebasestorage.app',
    iosBundleId: 'com.example.ungDungHocTiengAnh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA00nCu19ojVU93niKFJaUNmGc4ynBPyTc',
    // TODO: Nếu bạn dùng iOS/macOS, cần tạo app macOS trong Firebase a0580 để lấy appId đúng.
    appId: '1:16215337124:android:c49d3bb0968e33ae175e31',
    messagingSenderId: '16215337124',
    projectId: 'ung-dung-hoc-tieng-anh-a0580',
    storageBucket: 'ung-dung-hoc-tieng-anh-a0580.firebasestorage.app',
    iosBundleId: 'com.example.ungDungHocTiengAnh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA00nCu19ojVU93niKFJaUNmGc4ynBPyTc',
    appId: '1:16215337124:android:c49d3bb0968e33ae175e31',
    messagingSenderId: '16215337124',
    projectId: 'ung-dung-hoc-tieng-anh-a0580',
    authDomain: 'ung-dung-hoc-tieng-anh-a0580.firebaseapp.com',
    storageBucket: 'ung-dung-hoc-tieng-anh-a0580.firebasestorage.app',
  );
}
